object Main {

    @JvmStatic
    fun main(args: Array<String>) {
//        println("AdventOfCode2022!")
//        twoTwo.One.resolve()
//        twoTwo.Two.resolve()
//        twoTwo.Three.resolve()
//        twoTwo.Four.resolve()
//        twoTwo.Five.resolve()
//        twoTwo.Six.resolve()
//        twoTwo.Seven.resolve()
//        twoTwo.Eight.resolve()
//        twoTwo.Eleven.resolve()
//        twoTwo.ElevenTwo.resolve()

//        println("AdventOfCode2023!")
//        twoThree.One.resolve()
//        twoThree.Two.resolve()
//        twoThree.Three.resolve()
//        twoThree.Four.resolve()
//        twoThree.Five.resolve()
//        twoThree.Six.resolve()
//        twoThree.Seven.resolve()
//        twoThree.Eight.resolve()
//        twoThree.Nine.resolve()
//        twoThree.Ten.resolve()
//        twoThree.Eleven.resolve()
//        twoThree.Thirteen.resolve()
//        twoThree.Fourteen.resolve()
//        twoThree.Sixteen.resolve()
//        twoThree.Eighteen.resolve()

        println("AdventOfCode2024!")
//        twoFour.One.resolve()
//        twoFour.Two.resolve()
//        twoFour.Three.resolve()
//        twoFour.Four.resolve()
//        twoFour.Five.resolve()
//        twoFour.Six.resolve()
//        twoFour.Seven.resolve()
//        twoFour.Eight.resolve()
        twoFour.Nine.resolve()
    }
}